services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./secrets:${SSL_PATH}
      - ./static:/app/static
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network
    volumes:
      - redis-volume:/data

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - app-network
    ports:
      - '5050:80'
    depends_on:
      - db

networks:
  app-network:

volumes:
  redis-volume:
  postgres-volume:
